services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=database
    ports:
      - 27017:27017
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/database
    depends_on:
      - mongo
